-- Add show_comments column to profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS show_comments boolean DEFAULT true;

-- Drop and recreate get_public_profile function with show_comments
DROP FUNCTION IF EXISTS public.get_public_profile(text);

CREATE FUNCTION public.get_public_profile(p_username text)
RETURNS TABLE(
  accent_color text,
  animated_title boolean,
  ascii_size integer,
  ascii_waves boolean,
  audio_volume integer,
  avatar_shape text,
  avatar_url text,
  background_color text,
  background_effect text,
  background_url text,
  background_video_url text,
  bio text,
  card_border_color text,
  card_border_enabled boolean,
  card_border_width integer,
  card_color text,
  card_style text,
  created_at timestamp with time zone,
  custom_cursor_url text,
  discord_avatar_decoration boolean,
  discord_badge_color text,
  discord_card_opacity integer,
  discord_card_style text,
  discord_show_badge boolean,
  discord_user_id text,
  dislikes_count integer,
  display_name text,
  display_name_animation text,
  effects_config jsonb,
  enable_profile_gradient boolean,
  glow_badges boolean,
  glow_socials boolean,
  glow_username boolean,
  icon_color text,
  icon_links_opacity integer,
  icon_only_links boolean,
  id uuid,
  is_premium boolean,
  layout_style text,
  likes_count integer,
  location text,
  monochrome_icons boolean,
  music_url text,
  name_font text,
  occupation text,
  og_description text,
  og_icon_url text,
  og_image_url text,
  og_title text,
  og_title_animation text,
  profile_blur integer,
  profile_opacity integer,
  show_avatar boolean,
  show_badges boolean,
  show_comments boolean,
  show_description boolean,
  show_display_name boolean,
  show_likes boolean,
  show_links boolean,
  show_username boolean,
  show_views boolean,
  show_volume_control boolean,
  start_screen_animation text,
  start_screen_bg_color text,
  start_screen_color text,
  start_screen_enabled boolean,
  start_screen_font text,
  start_screen_text text,
  swap_bio_colors boolean,
  text_color text,
  text_font text,
  transparent_badges boolean,
  uid_number integer,
  updated_at timestamp with time zone,
  use_discord_avatar boolean,
  username text,
  views_count integer
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    p.accent_color,
    p.animated_title,
    p.ascii_size,
    p.ascii_waves,
    p.audio_volume,
    p.avatar_shape,
    p.avatar_url,
    p.background_color,
    p.background_effect,
    p.background_url,
    p.background_video_url,
    p.bio,
    p.card_border_color,
    p.card_border_enabled,
    p.card_border_width,
    p.card_color,
    p.card_style,
    p.created_at,
    p.custom_cursor_url,
    p.discord_avatar_decoration,
    p.discord_badge_color,
    p.discord_card_opacity,
    p.discord_card_style,
    p.discord_show_badge,
    p.discord_user_id,
    p.dislikes_count,
    p.display_name,
    p.display_name_animation,
    p.effects_config,
    p.enable_profile_gradient,
    p.glow_badges,
    p.glow_socials,
    p.glow_username,
    p.icon_color,
    p.icon_links_opacity,
    p.icon_only_links,
    p.id,
    p.is_premium,
    p.layout_style,
    p.likes_count,
    p.location,
    p.monochrome_icons,
    p.music_url,
    p.name_font,
    p.occupation,
    p.og_description,
    p.og_icon_url,
    p.og_image_url,
    p.og_title,
    p.og_title_animation,
    p.profile_blur,
    p.profile_opacity,
    p.show_avatar,
    p.show_badges,
    p.show_comments,
    p.show_description,
    p.show_display_name,
    p.show_likes,
    p.show_links,
    p.show_username,
    p.show_views,
    p.show_volume_control,
    p.start_screen_animation,
    p.start_screen_bg_color,
    p.start_screen_color,
    p.start_screen_enabled,
    p.start_screen_font,
    p.start_screen_text,
    p.swap_bio_colors,
    p.text_color,
    p.text_font,
    p.transparent_badges,
    p.uid_number,
    p.updated_at,
    p.use_discord_avatar,
    p.username,
    p.views_count
  FROM profiles p
  WHERE lower(p.username) = lower(p_username);
$$;

-- Drop and recreate get_public_profile_by_alias function with show_comments
DROP FUNCTION IF EXISTS public.get_public_profile_by_alias(text);

CREATE FUNCTION public.get_public_profile_by_alias(p_alias text)
RETURNS TABLE(
  accent_color text,
  animated_title boolean,
  ascii_size integer,
  ascii_waves boolean,
  audio_volume integer,
  avatar_shape text,
  avatar_url text,
  background_color text,
  background_effect text,
  background_url text,
  background_video_url text,
  bio text,
  card_border_color text,
  card_border_enabled boolean,
  card_border_width integer,
  card_color text,
  card_style text,
  created_at timestamp with time zone,
  custom_cursor_url text,
  discord_avatar_decoration boolean,
  discord_badge_color text,
  discord_card_opacity integer,
  discord_card_style text,
  discord_show_badge boolean,
  discord_user_id text,
  dislikes_count integer,
  display_name text,
  display_name_animation text,
  effects_config jsonb,
  enable_profile_gradient boolean,
  glow_badges boolean,
  glow_socials boolean,
  glow_username boolean,
  icon_color text,
  icon_links_opacity integer,
  icon_only_links boolean,
  id uuid,
  is_premium boolean,
  layout_style text,
  likes_count integer,
  location text,
  monochrome_icons boolean,
  music_url text,
  name_font text,
  occupation text,
  og_description text,
  og_icon_url text,
  og_image_url text,
  og_title text,
  og_title_animation text,
  profile_blur integer,
  profile_opacity integer,
  show_avatar boolean,
  show_badges boolean,
  show_comments boolean,
  show_description boolean,
  show_display_name boolean,
  show_likes boolean,
  show_links boolean,
  show_username boolean,
  show_views boolean,
  show_volume_control boolean,
  start_screen_animation text,
  start_screen_bg_color text,
  start_screen_color text,
  start_screen_enabled boolean,
  start_screen_font text,
  start_screen_text text,
  swap_bio_colors boolean,
  text_color text,
  text_font text,
  transparent_badges boolean,
  uid_number integer,
  updated_at timestamp with time zone,
  use_discord_avatar boolean,
  username text,
  views_count integer
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    p.accent_color,
    p.animated_title,
    p.ascii_size,
    p.ascii_waves,
    p.audio_volume,
    p.avatar_shape,
    p.avatar_url,
    p.background_color,
    p.background_effect,
    p.background_url,
    p.background_video_url,
    p.bio,
    p.card_border_color,
    p.card_border_enabled,
    p.card_border_width,
    p.card_color,
    p.card_style,
    p.created_at,
    p.custom_cursor_url,
    p.discord_avatar_decoration,
    p.discord_badge_color,
    p.discord_card_opacity,
    p.discord_card_style,
    p.discord_show_badge,
    p.discord_user_id,
    p.dislikes_count,
    p.display_name,
    p.display_name_animation,
    p.effects_config,
    p.enable_profile_gradient,
    p.glow_badges,
    p.glow_socials,
    p.glow_username,
    p.icon_color,
    p.icon_links_opacity,
    p.icon_only_links,
    p.id,
    p.is_premium,
    p.layout_style,
    p.likes_count,
    p.location,
    p.monochrome_icons,
    p.music_url,
    p.name_font,
    p.occupation,
    p.og_description,
    p.og_icon_url,
    p.og_image_url,
    p.og_title,
    p.og_title_animation,
    p.profile_blur,
    p.profile_opacity,
    p.show_avatar,
    p.show_badges,
    p.show_comments,
    p.show_description,
    p.show_display_name,
    p.show_likes,
    p.show_links,
    p.show_username,
    p.show_views,
    p.show_volume_control,
    p.start_screen_animation,
    p.start_screen_bg_color,
    p.start_screen_color,
    p.start_screen_enabled,
    p.start_screen_font,
    p.start_screen_text,
    p.swap_bio_colors,
    p.text_color,
    p.text_font,
    p.transparent_badges,
    p.uid_number,
    p.updated_at,
    p.use_discord_avatar,
    p.username,
    p.views_count
  FROM profiles p
  WHERE lower(p.alias_username) = lower(p_alias);
$$;