-- First drop the existing functions
DROP FUNCTION IF EXISTS public.get_public_profile(text);
DROP FUNCTION IF EXISTS public.get_public_profile_by_alias(text);

-- Recreate get_public_profile function with show_likes field
CREATE FUNCTION public.get_public_profile(p_username text)
RETURNS TABLE (
  id uuid,
  username text,
  display_name text,
  bio text,
  avatar_url text,
  background_url text,
  background_color text,
  accent_color text,
  card_color text,
  effects_config jsonb,
  music_url text,
  views_count integer,
  uid_number integer,
  created_at timestamptz,
  updated_at timestamptz,
  background_video_url text,
  avatar_shape text,
  name_font text,
  text_font text,
  occupation text,
  location text,
  discord_user_id text,
  layout_style text,
  card_style text,
  text_color text,
  icon_color text,
  custom_cursor_url text,
  og_title text,
  og_description text,
  og_image_url text,
  og_icon_url text,
  og_title_animation text,
  background_effect text,
  discord_card_style text,
  discord_badge_color text,
  discord_card_opacity integer,
  discord_show_badge boolean,
  discord_avatar_decoration boolean,
  use_discord_avatar boolean,
  start_screen_enabled boolean,
  start_screen_text text,
  start_screen_font text,
  start_screen_color text,
  start_screen_bg_color text,
  start_screen_animation text,
  show_volume_control boolean,
  show_username boolean,
  show_badges boolean,
  show_views boolean,
  show_avatar boolean,
  show_links boolean,
  show_description boolean,
  show_display_name boolean,
  card_border_enabled boolean,
  card_border_width integer,
  card_border_color text,
  audio_volume real,
  profile_opacity integer,
  profile_blur integer,
  monochrome_icons boolean,
  animated_title boolean,
  swap_bio_colors boolean,
  glow_username boolean,
  glow_socials boolean,
  glow_badges boolean,
  enable_profile_gradient boolean,
  icon_only_links boolean,
  icon_links_opacity integer,
  transparent_badges boolean,
  ascii_size integer,
  ascii_waves boolean,
  is_premium boolean,
  display_name_animation text,
  likes_count integer,
  dislikes_count integer,
  show_likes boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id,
    p.username,
    p.display_name,
    p.bio,
    p.avatar_url,
    p.background_url,
    p.background_color,
    p.accent_color,
    p.card_color,
    p.effects_config,
    p.music_url,
    p.views_count,
    p.uid_number,
    p.created_at,
    p.updated_at,
    p.background_video_url,
    p.avatar_shape,
    p.name_font,
    p.text_font,
    p.occupation,
    p.location,
    p.discord_user_id,
    p.layout_style,
    p.card_style,
    p.text_color,
    p.icon_color,
    p.custom_cursor_url,
    p.og_title,
    p.og_description,
    p.og_image_url,
    p.og_icon_url,
    p.og_title_animation,
    p.background_effect,
    p.discord_card_style,
    p.discord_badge_color,
    p.discord_card_opacity,
    p.discord_show_badge,
    p.discord_avatar_decoration,
    p.use_discord_avatar,
    p.start_screen_enabled,
    p.start_screen_text,
    p.start_screen_font,
    p.start_screen_color,
    p.start_screen_bg_color,
    p.start_screen_animation,
    p.show_volume_control,
    p.show_username,
    p.show_badges,
    p.show_views,
    p.show_avatar,
    p.show_links,
    p.show_description,
    p.show_display_name,
    p.card_border_enabled,
    p.card_border_width,
    p.card_border_color,
    p.audio_volume,
    p.profile_opacity,
    p.profile_blur,
    p.monochrome_icons,
    p.animated_title,
    p.swap_bio_colors,
    p.glow_username,
    p.glow_socials,
    p.glow_badges,
    p.enable_profile_gradient,
    p.icon_only_links,
    p.icon_links_opacity,
    p.transparent_badges,
    p.ascii_size,
    p.ascii_waves,
    p.is_premium,
    p.display_name_animation,
    p.likes_count,
    p.dislikes_count,
    COALESCE(p.show_likes, true)
  FROM profiles p
  WHERE LOWER(p.username) = LOWER(p_username);
END;
$$;

-- Recreate get_public_profile_by_alias function with show_likes field
CREATE FUNCTION public.get_public_profile_by_alias(p_alias text)
RETURNS TABLE (
  id uuid,
  username text,
  display_name text,
  bio text,
  avatar_url text,
  background_url text,
  background_color text,
  accent_color text,
  card_color text,
  effects_config jsonb,
  music_url text,
  views_count integer,
  uid_number integer,
  created_at timestamptz,
  updated_at timestamptz,
  background_video_url text,
  avatar_shape text,
  name_font text,
  text_font text,
  occupation text,
  location text,
  discord_user_id text,
  layout_style text,
  card_style text,
  text_color text,
  icon_color text,
  custom_cursor_url text,
  og_title text,
  og_description text,
  og_image_url text,
  og_icon_url text,
  og_title_animation text,
  background_effect text,
  discord_card_style text,
  discord_badge_color text,
  discord_card_opacity integer,
  discord_show_badge boolean,
  discord_avatar_decoration boolean,
  use_discord_avatar boolean,
  start_screen_enabled boolean,
  start_screen_text text,
  start_screen_font text,
  start_screen_color text,
  start_screen_bg_color text,
  start_screen_animation text,
  show_volume_control boolean,
  show_username boolean,
  show_badges boolean,
  show_views boolean,
  show_avatar boolean,
  show_links boolean,
  show_description boolean,
  show_display_name boolean,
  card_border_enabled boolean,
  card_border_width integer,
  card_border_color text,
  audio_volume real,
  profile_opacity integer,
  profile_blur integer,
  monochrome_icons boolean,
  animated_title boolean,
  swap_bio_colors boolean,
  glow_username boolean,
  glow_socials boolean,
  glow_badges boolean,
  enable_profile_gradient boolean,
  icon_only_links boolean,
  icon_links_opacity integer,
  transparent_badges boolean,
  ascii_size integer,
  ascii_waves boolean,
  is_premium boolean,
  display_name_animation text,
  likes_count integer,
  dislikes_count integer,
  show_likes boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id,
    p.username,
    p.display_name,
    p.bio,
    p.avatar_url,
    p.background_url,
    p.background_color,
    p.accent_color,
    p.card_color,
    p.effects_config,
    p.music_url,
    p.views_count,
    p.uid_number,
    p.created_at,
    p.updated_at,
    p.background_video_url,
    p.avatar_shape,
    p.name_font,
    p.text_font,
    p.occupation,
    p.location,
    p.discord_user_id,
    p.layout_style,
    p.card_style,
    p.text_color,
    p.icon_color,
    p.custom_cursor_url,
    p.og_title,
    p.og_description,
    p.og_image_url,
    p.og_icon_url,
    p.og_title_animation,
    p.background_effect,
    p.discord_card_style,
    p.discord_badge_color,
    p.discord_card_opacity,
    p.discord_show_badge,
    p.discord_avatar_decoration,
    p.use_discord_avatar,
    p.start_screen_enabled,
    p.start_screen_text,
    p.start_screen_font,
    p.start_screen_color,
    p.start_screen_bg_color,
    p.start_screen_animation,
    p.show_volume_control,
    p.show_username,
    p.show_badges,
    p.show_views,
    p.show_avatar,
    p.show_links,
    p.show_description,
    p.show_display_name,
    p.card_border_enabled,
    p.card_border_width,
    p.card_border_color,
    p.audio_volume,
    p.profile_opacity,
    p.profile_blur,
    p.monochrome_icons,
    p.animated_title,
    p.swap_bio_colors,
    p.glow_username,
    p.glow_socials,
    p.glow_badges,
    p.enable_profile_gradient,
    p.icon_only_links,
    p.icon_links_opacity,
    p.transparent_badges,
    p.ascii_size,
    p.ascii_waves,
    p.is_premium,
    p.display_name_animation,
    p.likes_count,
    p.dislikes_count,
    COALESCE(p.show_likes, true)
  FROM profiles p
  WHERE LOWER(p.alias_username) = LOWER(p_alias);
END;
$$;